import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './Navbar'; // เช็ค path ให้ถูกต้องนะครับ
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col bg-neutral-950">
        {/* Navbar วางไว้เหมือนเดิม */}
        <Navbar /> 
        
        {/* แก้ไขตรงนี้: ห่อ children ด้วย div และเพิ่ม pt-20 (Padding Top) 
            เพื่อให้เนื้อหาขยับลงมาพ้นความสูงของ Navbar ในทุกหน้าครับ */}
        <div className="flex-grow pt-20 md:pt-24">
          {children}
        </div>
        
      </body>
    </html>
  );
}